#pragma once

#define ID_TABCTRL 1000
#define ID_IDTAB 1001
#define ID_IDTAB_UPDATE 1021
#define ID_ACTIVITIESTAB 1002
#define ID_ACTIVITIESTAB_UPDATE 1022
#define ID_ACTIVITIESTAB_DRAW_DAY 1023
#define ID_ACTIVITIESTAB_UPDATE_TIME 1031
#define ID_ACTIVITIESTAB_UPDATE_ACTIVITIES 1032
#define ID_ACTIVITIESTAB_RESET 1033
#define ID_VEHICLESTAB 1003

// buttons
#define ID_ACTIVITIESTAB_LBUTTON 1501
#define ID_ACTIVITIESTAB_RBUTTON 1502

#include "functions.hpp"

LRESULT CALLBACK MainWndProc(HWND hMainWindow, UINT msg, WPARAM wParam, LPARAM lParam);